server:
  port: 8080

spring:
  application:
    name: properties-example

app:
  name: 스프링 부트 속성 바인딩 예제
  description: 스프링 부트의 다양한 속성 바인딩 방법을 보여주는 애플리케이션
  version: 1.0.0
  enabled: true
  timeout: 10s
  max-size: 100MB
  
  server:
    host: example.com
    port: 9090
  
  list-values:
    - 값1
    - 값2
    - 값3
  
  map-values:
    key1: 값1
    key2: 값2
    key3: 값3
  
  nested:
    name: 중첩된 속성
    value: 100 